display:
  default:
    display_options:
      fields:
        media_bulk_form:
          action_title: Actie
      filters:
        name:
          expose:
            label: Naam
  page:
    display_options:
      fields:
        media_bulk_form:
          action_title: Actie
        edit_media:
          text: Bewerken
  widget:
    display_options:
      filters:
        name:
          expose:
            label: Naam
  widget_table:
    display_options:
      fields:
        name:
          label: Naam
      filters:
        name:
          expose:
            label: Naam
