links:
  -
    path: /
    priority: '1.0'
    changefreq: daily
  -
    path: /forms
    priority: '0.8'
    changefreq: weekly
  -
    path: /guides
    priority: '0.8'
    changefreq: weekly
  -
    path: /events
    priority: '0.7'
    changefreq: daily
